Introduce stateless mode
Allows to use DEKU in stateless mode without requiring to initialize a
project for every kernel build. Now to build a livepatch module or
deploy changes to the running kernel the build directory path must be
provided. Additionally the “--target” parameter is required for ssh
connection to the target.

diff --git a/deku b/deku
--- a/deku
+++ b/deku
@@ -5,6 +5,8 @@
 #
 # Main file for DEKU
 
+export CURRENT_DIR=`pwd`
+
 MAIN_PATH=`realpath "$0"`
 MAIN_PATH=`dirname "$MAIN_PATH"`
 cd "$MAIN_PATH"
@@ -12,35 +14,74 @@ cd "$MAIN_PATH"
 . ./header.sh
 . ./common.sh
 
-showHelp()
+showCrosHelp()
 {
 	echo "DEKU is a tool that allow quick apply changes to the running kernel on the device.
 The changes provided by DEKU lives in the kernel util next reboot.
 
 Usage:
-    deku [OPTIONS...] COMMAND
+    deku --board=<CHROMEBOOK_BOARD_NAME> --target=<DUT_ADDRESS[:PORT]> COMMAND
 Commands list:
-    init   - initialize the DEKU. Create a workdir directory where the configuration file, current state of the kernel source code and kernel image version on the device are stored,
-    build  - build the DEKU modules which are livepatch kernel's modules,
-    sync   - synchronize current state of source code and kernel image. It must be used when the kernel was build by user and flashed to the device,
-    deploy - build and deploy the changes to the device.
+    build                                 build the DEKU modules which are livepatch kernel's modules,
+    deploy                                build and deploy the changes to the device.
 
-'init' command options:
-    -b <PATH_TO_KERNEL_BUILD_DIR> [-s <PATH_TO_KERNEL_SOURCES_DIR>] [--board=<CHROMEBOOK_BOARD_NAME>] -d ssh -p <USER@DUT_ADDRESS[:PORT]>
+Avaiable parameters:
+    --board=<BOARD>                       board name. Meaning of this parameter is the same as in
+                                          the ChromiumOS SDK,
+    --target=<DUT_ADDRESS[:PORT]>         IP address with optional SSH port to the target device.
 
-    -b path to kernel build directory,
-    -s path to kernel sources directory. Use this parameter if initialization process can't find kernel sources dir,
-    --board (Only avaiable inside ChromiumOS SDK) board name. Meaning of this parameter is the same as in the ChromiumOS SDK. If this parameter is used then -b ans -s parameters can be skipped,
-    -d method used to upload and deploy livepatch modules to the DUT. Currently only the 'ssh' is supported,
-    -p parameters for deploy method. For the 'ssh' deploy method, pass the user and DUT address. Optional pass the port number after colon. Additional ssh parameters like '-o' can be passed after space,
-       The given user must be able to load and unload kernel modules. The SSH must be configured to use key-based authentication.
-
-	Example usage:
-		./deku -b /home/user/linux_build -d ssh -p root@192.168.0.100:2233 init
-
-	Example usage when custom key-based authentication key is used for ssh connection:
-		./deku -b /home/user/linux_build -d ssh -p \"root@192.168.0.100 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i ~/key_rsa\" init
+Example usage:
+    ./deku --board=brya --target=192.168.0.100 deploy
 	"
+}
+
+showHelp()
+{
+	if [[ -e /etc/cros_chroot_version ]]; then
+		showCrosHelp
+		return
+	fi
+
+	echo "DEKU is a tool that allow quick apply changes to the running kernel on the device.
+The changes provided by DEKU lives in the kernel util next reboot.
+
+Usage:
+    deku -b <PATH_TO_KERNEL_BUILD_DIR> [--board=<CHROMEBOOK_BOARD_NAME>] --target <USER@DUT_ADDRESS[:PORT]> COMMAND
+Commands list:
+    build                                 build the DEKU modules which are livepatch kernel's modules,
+    deploy                                build and deploy the changes to the device.
+    sync                                  synchronize information about kernel source code.
+                                          Use this command after building the kernel. The use of
+                                          this command is not mandatory, but it will make DEKU work
+                                          more reliably. When the --src_inst_dir parameter is used,
+                                          executing this command after the kernel is built is
+                                          unnecessary as DEKU will run more reliably.
+
+Avaiable parameters:
+    -b, --builddir                        path to kernel build directory,
+    -s, --sourcesdir                      path to kernel sources directory. Use this parameter
+                                          if DEKU can't find kernel sources dir,
+    --board=<BOARD>                       (Only avaiable inside ChromiumOS SDK) board name. Meaning
+                                          of this parameter is the same as in the ChromiumOS SDK.
+                                          If this parameter is used then -b and -s parameters can
+                                          be skipped,
+    --target=<USER@DUT_ADDRESS[:PORT]>    SSH connection parameter to the target device. The given
+                                          user must be able to load and unload kernel modules. The
+                                          SSH must be configured to use key-based authentication.
+                                          Below is an example with this parameter,
+    --ssh_options=<\"-o ...\">              options for SSH. Below is an example with this parameter,
+    --src_inst_dir=<PATH>                 directory with the kernel sources that were installed after
+                                          the kernel was built. Having this directory makes DEKU
+                                          working more reliable. As an alternative to this
+                                          parameter, the 'deku sync' command can be executed after
+                                          the kernel has been built to make DEKU work more reliably,
+
+Example usage:
+    ./deku -b /home/user/linux_build --target=root@192.168.0.100:2200 deploy
+
+Example usage when custom key-based authentication key is used for ssh connection:
+    ./deku -b /home/user/linux_build --target=root@192.168.0.100 --ssh_options=\"-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i ~/key_rsa\" deploy
+    "
 }
 
 exportVars()
@@ -71,80 +112,72 @@ checkIfUpdated()
 
 main()
 {
-	local workdir="$DEFAULT_WORKDIR"
 	for ((i=1; i<=$#; i++))
 	do
 		local opt=${!i}
-		if [[ $opt == "-w" ]]; then
-			((i++))
-			workdir="${!i}"
-			break
-		fi
+		[[ $opt == "-h" || $opt == "--help" ]] && { showHelp; exit; }
 	done
 
-	# detect whether we're inside a chromeos chroot
-	if [[ -e /etc/cros_chroot_version ]]; then
-		. ./integration/cros_prepare.sh "$@"
-		local rc=$?
-		[[ $rc != 0 ]] && exit $rc
-		[[ "$CROS_WORKDIR" ]] && workdir="$CROS_WORKDIR"
+	source "init_vars.sh" "$@"
+	rc=$?
+	if [ $rc != $NO_ERROR ]; then
+		exit $rc
 	fi
 
 	exportVars "$workdir"
 	checkIfUpdated
 
-	for ((i=1; i<=$#; i++))
-	do
-		local opt=${!i}
-		[[ $opt == "-h" || $opt == "--help" ]] && { showHelp; exit; }
-		if [[ $opt == "-w" ]]; then
-			((i++))
-			continue
-		fi
-		if [[ -f "$COMMANDS_DIR/$opt.sh" ]]; then
-			local rc=$NO_ERROR
-			if [[ "$opt" == "init" ]]; then
-				bash "$COMMANDS_DIR/$opt.sh" "$@"
-				rc=$?
-				if [[ "$rc" == $NO_ERROR ]]; then
-					exportVars "$workdir"
-					bash "$COMMANDS_DIR/sync.sh" auto
-					rc=$?
-					if [[ "$rc" == $NO_ERROR ]]; then
-						logInfo "Init done"
-					fi
-				fi
-			else
-				if [ ! -d "$workdir" ]; then
-					logInfo "Can't find $workdir directory"
-					logInfo "The project probably has not been initiated"
-					rc=$ERROR_NO_WORKDIR
-				elif [[ "$KERN_SRC_INSTALL_DIR" && ! -d "$KERN_SRC_INSTALL_DIR" ]]; then
-					if [[ "$CHROMEOS_CHROOT" == 1 ]]; then
-						logErr "ERROR: Your kernel must be build with: USE=\"livepatch kernel_sources\" emerge-$board chromeos-kernel-..."
-					else
-						logErr "Can't find installation dir with kernel sources ("$KERN_SRC_INSTALL_DIR")."
-						logErr "You must undo any changes made after the kernel was built and install kernel sources."
-					fi
-					exit $ERROR_INSUFFICIENT_BUILD_PARAMS
-				else
-					if [[ "$KERN_SRC_INSTALL_DIR" ]]; then
-						[ "$KERN_SRC_INSTALL_DIR" -nt "$KERNEL_VERSION_FILE" ] || \
-						[ "$KERN_SRC_INSTALL_DIR" -ot "$KERNEL_VERSION_FILE" ] && \
-						bash "$COMMANDS_DIR/sync.sh" auto
-					fi
-					bash "$COMMANDS_DIR/$opt.sh"
-					rc=$?
-				fi
-			fi
-			if [ $rc != $NO_ERROR ]; then
-				echo -e "${RED}Fail!${NC}"
-			fi
-			exit $rc
-		fi
-	done
+	# cache the information about modified files
+	export CASHED_MODIFIED_FILES="$(modifiedFiles)"
 
-	showHelp
+	# check if kernel was updated
+	if [[ -f "$KERNEL_VERSION_FILE" ]]; then
+		local currKernVer=$(getKernelVersion)
+		local prevKernVer=$(<$KERNEL_VERSION_FILE)
+
+		[[ "$currKernVer" != "$prevKernVer" ]] && \
+			bash "$COMMANDS_DIR/sync.sh" auto 1
+
+		[[ "$KERN_SRC_INSTALL_DIR" && \
+		   "$KERN_SRC_INSTALL_DIR" -nt "$KERNEL_VERSION_FILE" ]] && \
+			bash "$COMMANDS_DIR/sync.sh" auto 2
+	else
+		getKernelVersion > "$KERNEL_VERSION_FILE"
+	fi
+
+	local command=${@: -1}
+	if [[ ! -f "$COMMANDS_DIR/$command.sh" ]]; then
+		if [[ "$command" == "init" ]]; then
+			logErr "$command command has been removed."
+			logErr "Please look to the README for more information"
+			exit $ERROR_INVALID_PARAMETERS
+		else
+			logErr "Command '$command' not found"
+		fi
+		showHelp
+		exit $ERROR_INVALID_PARAMETERS
+	fi
+
+	local rc=$NO_ERROR
+	if [ ! -d "$workdir" ]; then
+		logWarn "Can't find $workdir directory"
+		rc=$ERROR_NO_WORKDIR
+	elif [[ "$KERN_SRC_INSTALL_DIR" && ! -d "$KERN_SRC_INSTALL_DIR" ]]; then
+		if [[ "$CHROMEOS_CHROOT" == 1 ]]; then
+			logErr "ERROR: Your kernel must be build with: USE=\"livepatch kernel_sources\" emerge-$board chromeos-kernel-..."
+		else
+			logErr "Can't find installation dir with kernel sources ($KERN_SRC_INSTALL_DIR)."
+			logErr "You must undo any changes made after the kernel was built and install kernel sources to the $KERN_SRC_INSTALL_DIR"
+		fi
+		exit $ERROR_INSUFFICIENT_BUILD_PARAMS
+	else
+		bash "$COMMANDS_DIR/$command.sh"
+		rc=$?
+	fi
+	if [ $rc != $NO_ERROR ]; then
+		echo -e "${RED}Fail!${NC}"
+	fi
+	exit $rc
 }
 
 main "$@"
